### ISSUE TITLE
Updated to latest Murlock version 3.2.0, brings a new bug (AsyncStorageManagerException).

### ISSUE THREAD

**Issue by OsoianMarcel** [felanios/murlock#40] opened 2024-02-29 08:49 UTC
Calling the Murlock service - `await this.murLockService.lock(lockName, 5e3);`

Throws this error:

```
{
  "type": "AsyncStorageManagerException",
  "message": "No active store found",
  "stack":
      AsyncStorageManagerException: No active store found
          at AsyncStorageManager.get (/home/node/app/node_modules/murlock/lib/als/als-manager.ts:24:13)
          at MurLockService.getClientId (/home/node/app/node_modules/murlock/lib/murlock.service.ts:55:45)
          at MurLockService.<anonymous> (/home/node/app/node_modules/murlock/lib/murlock.service.ts:121:27)
          at Generator.next (<anonymous>)
          at /home/node/app/node_modules/murlock/dist/murlock.service.js:20:71
          at new Promise (<anonymous>)
          at __awaiter (/home/node/app/node_modules/murlock/dist/murlock.service.js:16:12)
          at MurLockService.unlock (/home/node/app/node_modules/murlock/dist/murlock.service.js:118:16)
          ...
          at processTicksAndRejections (node:internal/process/task_queues:95:5)
  "name": "AsyncStorageManagerException"
}
```

The prev. version 3.0.1 worked just fine.

**Comment by felanios** [comment] 2024-02-29 11:22
Hi @OsoianMarcel, which node version are you using? Also, did you encounter this problem while using decorator?

**Comment by powerofsoul** [comment] 2024-03-01 11:05
I do experience the same issue. I am using the decorator and I have node `v18.19.0`. Version `3.0.1` works perfectly but version `3.2.0` just throws the op error.

**Comment by OsoianMarcel** [comment] 2024-03-01 16:56
> Hi @OsoianMarcel, which node version are you using? Also, did you encounter this problem while using decorator?

Node version: **v20.11.0**
I'm using the service, not decorator.

**Comment by Scoup** [comment] 2024-03-08 14:16
I'm experiencing the same issue with 3.1.0 or 3.2.0. I'm using version 3.1.0-beta.1, which works just fine.

However, the issue is related to [this](https://github.com/felanios/murlock/blob/master/lib/als/als-manager.ts#L9-L11). The only way to have a store is by using the [interceptor](https://github.com/felanios/murlock/blob/master/lib/interceptors/async-local-storage.interceptor.ts#L12-L21).

If the application uses the service directly or is not using the `AsyncStorageInterceptor` interceptor, the store will not exist.

This approach was introduced to address [this issue](https://github.com/felanios/murlock/issues/33). However, it's a very specific scenario where the same application needs to lock the same context. Therefore, it probably should be applied only to those who have this requirement (manually), such as by adding a decorator to the endpoint or something similar.

**Comment by Scoup** [comment] 2024-03-08 14:44
I think maybe a solution could be to use the nestjs-cls again.

Since this issue is related to the context, this could be used on a decorator's "group".

Smething like this:

```
export function MurLockWrapperExample(ms: number, name: string) {
  return applyDecorators(
    UseCls(),
    MurLock(ms, name)
  );
}
```

**Comment by felanios** [comment] 2024-04-09 18:46
Hello @Scoup @powerofsoul @OsoianMarcel , I am very sorry that I could not solve the problem due to my health problems. I have released and tested a beta version for the solution, if you test it too, I can upgrade to the stable version.

https://www.npmjs.com/package/murlock/v/3.2.1-beta.1

**Comment by Scoup** [comment] 2024-04-09 19:06
@felanios I hope you're better. I have a lot of e2e tests on my application and mostly failed with this version, the same issue:
```
Unknown Error: Failed to acquire lock for key CacheService:updateUserReactions:b89e0d19-632b-48d3-97b3-3d873fbc964c:3fad9016-7790-4d2d-bace-068b86f0bf5f: No active store found
```

This is mostly a web socket project and doesn't use HTTP interceptors. I only use the decorator, like this:
```
  @MurLock(500, 'reaction.widgetId', 'reaction.itemId', 'reaction.userId')
  async updateReaction(reaction: Reaction) {
    const key = this.getReactionKey(reaction);
    await this.redis.set(key, JSON.stringify(reaction), 'EX', this.ttl);
  }
```

**Comment by felanios** [comment] 2024-04-09 19:15
@Scoup  Thank you I'm better now. Yes you are right, Murlock is not compatible with non-HTTP clients. Normally with nestjs-cls package it support non-HTTP clients, but nestjs-cls also come up with a different dependency problem.

**Comment by Scoup** [comment] 2024-04-09 19:56
> @Scoup Thank you I'm better now. Yes you are right, Murlock is not compatible with non-HTTP clients. Normally with nestjs-cls package it support non-HTTP clients, but nestjs-cls also come up with a different dependency problem.

What are the issues with nestjs-cls? The idea is to create a wrapper around some code and keep unique identifiers. Maybe we only need to think about where these will be this wrapper, like in the interceptor and/or in the decorators.

**Comment by felanios** [comment] 2024-04-09 20:29
@Scoup  https://github.com/felanios/murlock/issues/18 This is the issue about nestjs-cls. With 3.0.0 also I switched to  mount interceptor for non-http requests support and nestjs-cls perfectly support for this kind of clients.

**Comment by felanios** [comment] 2024-05-02 18:00
Hey guys, sorry for late update. https://www.npmjs.com/package/murlock/v/3.3.0-beta.1 I just released new beta version for non-http clients support. I'll just keep it as a beta version for now.

**Comment by Scoup** [comment] 2024-05-06 09:26
> Conflict with the AsyncLocalStorage (i think) #41

Great news! Thanks for the update!

**Comment by felanios** [comment] 2024-05-06 09:39
Hey @Scoup, I released the stable version also(https://www.npmjs.com/package/murlock/v/3.3.0). There were no problems when I tested it, but I still can't be sure what people will encounter. If you encounter any problems, I would appreciate it if you update this issue.

**Comment by felanios** [comment] 2024-05-12 11:36
Hey @Scoup, have you encountered any issues with the latest version? If not, I will close the issue.

**Comment by Scoup** [comment] 2024-05-13 13:07
> Hey @Scoup, have you encountered any issues with the latest version? If not, I will close the issue.

@felanios, no issue is working fine, and all tests passed! Thanks for the update.

**Closed** 2024-06-09 22:00 UTC
